sudo: required
services:
  - docker
env:
  global:
    - ID=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in docker-235005-18c61dab6682.json.enc -out docker-235005-18c61dab6682.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud componenets update kubectl
  - gcloud auth activate-service-account --key-file docker-235005-18c61dab6682.json
  - gcloud config set project docker-235005
  - gcloud conf set compute/zone us-east1-c
  - gcloud container cluster  get-credentials jino
  - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
  - docker build -t jjino/development -f image/test/Dockerfile ./image/test
script:
  - docker run jjino/development echo "jino" -- --coverage
deploy:
  provider: script
    script: bash deploy.sh
    on:
      branch: master
